---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: transfer the script file
    copy: src=/home/ubuntu/installDocker.sh dest=/tmp/
  - name: execute the script file
    command: sh /tmp/installDocker.sh
